import p1 from '../../assets/trophybanner.png';
import p2 from '../../assets/shopsense_banner.png';
import p3 from '../../assets/Image3.png';
import p4 from '../../assets/myjourneybanner.png';
import p5 from '../../assets/lms.png';
import p6 from '../../assets/unistore.png';
import p7 from '../../assets/techgrid.png';
import p8 from '../../assets/myportfolio.png';
import p9 from '../../assets/haven.png';

const projects = [

//Mobile Applications

  {
    category: 'mobile',
    award: 'no',
    type: 'GROUP PROJECT | COMPLETED',
    image: p1,
    altText: 'Trophy Project',
    title: 'Trophy - Employee Loyalty Rewarding System',
    description: '“Trophy” is a non-monetary token-based loyalty rewarding system to improve a company’s employees’ work experience.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'mobile',
    award: 'yes',
    type: 'GROUP PROJECT | ONGOING',
    image: p2,
    altText: 'ShopSense Project',
    title: 'ShopSense - Online Clothing Shopping for Blind People',
    description: '“ShopSense” provides online shopping accessibility for visually impaired people.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'mobile',
    award: 'no',
    type: 'GROUP PROJECT | COMPLETED',
    image: p5,
    altText: 'LMSSUSL - Learning Management System',
    title: 'LMSSUSL - Learning Management System',
    description: 'An interactive Learning Management System for educational institutions.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'mobile',
    award: 'yes',
    type: 'GROUP PROJECT | ONGOING',
    image: p4,
    altText: 'MYJOURNEY - AI Based Travel Planning',
    title: 'MYJOURNEY - AI Based Travel Planning',
    description: 'A personalization-AI based travel planning and booking app.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },

  //Web projects
  {
    category: 'web',
    award: 'no',
    type: 'GROUP PROJECT | COMPLETED',
    image: p6,
    altText: 'UniStore - Online Store for Preloved University Essentials',
    title: 'UniStore - Online Store for Preloved University Essentials',
    description: 'An e-commerce platform for university students to buy and sell second-hand items.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'web',
    award: 'no',
    type: 'GROUP PROJECT | COMPLETED',
    image: p6,
    altText: 'IEEE WIE Sri Lanka Section - Website Redesign',
    title: 'IEEE WIE Sri Lanka Section - Website Redesign',
    description: 'A redesigned website for the IEEE WIE Sri Lanka Section.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'web',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    image: p7,
    altText: 'TechGrid - E-Commerce Web Application',
    title: 'TechGrid - E-Commerce Web Application',
    description: 'An e-commerce platform for university students to buy and sell second-hand items.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'web',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    image: p8,
    altText: 'My Portfolio',
    title: 'My Portfolio',
    description: 'A responsive website to showcase my skills, projects, and achievements.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'web',
    award: 'yes',
    type: 'GROUP PROJECT | COMPLETED',
    image: p9,
    altText: 'Haven - Mental health oasis',
    title: 'Haven - Mental Health Oasis',
    description: 'It is a comprehensive online web-based platform that leverages AI and VR.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  

  //Other projects
  {
    category: 'other',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    showImage: false,
    image: p1,
    altText: 'Tumor Identifying AI Model',
    title: 'Tumor Identifying AI Model',
    description: 'An AI model created using Tensorflow/Keras and scikit-learn. This AI model is trained on real data from breast cancer diagnosis.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'other',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    showImage: false,
    image: p1,
    altText: 'JARVIS - AI Model',
    title: 'JARVIS - AI Model',
    description: 'This AI uses speech recognition and speech to text, to communicate with ChatGPT and talk back with ChatGPT\'s responses.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'other',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    showImage: false,
    image: p1,
    altText: 'Simple Tic-Tac-Toe Game',
    title: 'Simple Tic-Tac-Toe Game',
    description: 'To learn different Flutter things.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'other',
    award: 'yes',
    type: 'GROUP PROJECT | COMPLETED',
    image: p1,
    altText: 'Shut - Car Racing Simulation Game',
    title: 'Shut - Car Racing Simulation Game',
    description: 'To learn different Flutter things.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
];

export default projects;
