import p1 from '../../assets/trophybanner.png';
import p2 from '../../assets/shopsense_banner.png';
import p3 from '../../assets/Image3.png';
import p4 from '../../assets/myjourneybanner.png';
import p5 from '../../assets/lms.png';
import p6 from '../../assets/unistore.png';
import p7 from '../../assets/techgrid.png';
import p8 from '../../assets/myportfolio.png';
import p9 from '../../assets/haven.png';
import p10 from '../../assets/gjrti.png';
import p11 from '../../assets/wiebanner.png';
import blank from '../../assets/blank.png';
import p12 from '../../assets/projectbanners/ai.jpeg'
import p13 from '../../assets/projectbanners/jarvis.jpeg'
import p14 from '../../assets/projectbanners/sudoku.jpg'
import chemwaste from '../../assets/projectbanners/chemwaste.jpeg'

const projects = [

//Mobile Applications

  {
    category: 'mobile',
    award: 'no',
    type: 'GROUP PROJECT | COMPLETED',
    image: p1,
    altText: 'Trophy Project',
    title: 'Trophy - Employee Loyalty Rewarding System',
    description: '“Trophy” is a non-monetary token-based loyalty rewarding system to improve a company’s employees’ work experience.',
    github: 'https://github.com/disara7/Trophy',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'mobile',
    award: 'yes',
    type: 'GROUP PROJECT | ONGOING',
    image: p2,
    altText: 'ShopSense Project',
    title: 'ShopSense - Online Clothing Shopping for Blind People',
    description: '“ShopSense” provides online shopping accessibility for visually impaired people.',
    github: 'https://github.com/disara7/shopsense_app',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
    longdescription: 'ShopSense is a system that includes a mobile application that uses just “taps” on the screen and AI assistance for online clothing shopping, aiming to promote Inclusivity and accessibility to the visually impaired community, and a website for clothing item sellers to sell their items to these users.',
  },
  {
    category: 'mobile',
    award: 'no',
    type: 'GROUP PROJECT | COMPLETED',
    image: p5,
    altText: 'LMSSUSL - Learning Management System',
    title: 'LMSSUSL - Learning Management System',
    description: 'An interactive Learning Management System for educational institutions.',
    github: 'https://github.com/disara7/SUSL-LMS',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
    longdescription: 'SUSL LMS Mobile app is developed to elevate your learning experience. With this, you can seamlessly access courses, assignments, quizzes, and lecture recordings on the go. You can create and submit assignments, participate in interactive quizzes, and engage with peers via the forum. This helps you stay up to date with real-time notifications and personalize your profile with ease. To revolutionize your education journey – SUSL LMS brings you convenient and enriched learning.',
  },
  {
    category: 'mobile',
    award: 'yes',
    type: 'GROUP PROJECT | ONGOING',
    image: p4,
    altText: 'MYJOURNEY - AI Based Travel Planning',
    title: 'MYJOURNEY - AI Based Travel Planning',
    description: 'A personalization-AI based travel planning and booking app.',
    github: 'https://github.com/disara7/MyJourney',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
    longdescription: 'MyJourney is the next level travel planning app. It is a mobile application made to make travel planning easy depending on the category of tourist, and according to your budget. MyJourney categorizes tourists into six categories namely, Leisure tourist, Religious tourist, Cultural tourist, Eco tourist, Educational tourist, and Adventure tourist. The budget plan is given under three categories namely, Solo traveler, Couple and family and affordable accommodation could be booked through the app.',
  },
  // {
  //   category: 'mobile',
  //   award: 'yes',
  //   type: 'GROUP PROJECT | ONGOING',
  //   image: p4,
  //   altText: 'StyleUp - Clothing Rental Store',
  //   title: 'StyleUp - Clothing Rental Store',
  //   description: 'StyleUp is the one place to rent all your favorite styles as you desire from just around you, and even put cash in your pockets from your own closet.',
  //   github: 'https://github.com/disara7/MyJourney',
  //   adobe: 'https://adobe-link',
  //   medium: 'https://medium-link',
  //   video: 'https://video-link',
  //   longdescription: 'StyleUp is the one place to rent all your favorite styles as you desire from just around you, and even put cash in your pockets from your own closet. StyleUp offers a variety of clothing items ranging from elegant party wear, smart formal wear, perfect sportswear to bizarre drama costumes.',
  // },

  //Web projects
  {
    category: 'web',
    award: 'no',
    type: 'GROUP PROJECT | ONGOING',
    image: p10,
    altText: 'Management Information System for GJRTI',
    title: 'Management Information System for GJRTI',
    description: 'Complete MIS for Gem and Jewelry Research and Training Institute (GJRTI) - Ministry of Industries',
    github: 'https://github.com/disara7/GJRTI-Frontend',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
    longdescription: 'As our community project, me and my team is developing a fully customized web based Management Information System (MIS) [ERP System] from scratch for the Gem and Jewelry Research and Training Institute - Ministry of Industries, Sri Lanka.',
  },
  {
    category: 'web',
    award: 'no',
    type: 'GROUP PROJECT | COMPLETED',
    image: p6,
    altText: 'UniStore - Online Store for Preloved University Essentials',
    title: 'UniStore - Online Store for Preloved University Essentials',
    description: 'An e-commerce platform for university students to buy and sell second-hand items.',
    github: 'https://github.com/disara7/UniStore-web-project',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
    longdescription: 'UniStore is an innovative online web platform designed for university communities. It helps students exchange items and support each other’s businesses. The platform has two main sections: “Preloved” for second-hand items and “CraftsWorld” for handmade goods. UniStore encourages upcycling and helps students develop their entrepreneurial skills.',
  },
  {
    category: 'web',
    award: 'no',
    type: 'GROUP PROJECT | COMPLETED',
    image: p11,
    altText: 'IEEE WIE Sri Lanka Section - Website Redesign',
    title: 'IEEE WIE Sri Lanka Section - Website Redesign',
    description: 'A redesigned website for the IEEE WIE Sri Lanka Section.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'web',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    image: p7,
    altText: 'TechGrid - E-Commerce Web Application',
    title: 'TechGrid - E-Commerce Web Application',
    description: 'An e-commerce platform for university students to buy and sell second-hand items.',
    github: 'https://github.com/disara7/Tech-Grid',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
    longdescription: 'E-commerce platform with essential functionalities such as User Registration, User Profile Management Product Management (Add, Edit, View and Delete Products), and Order Management developed with Java, Spring boot, and Thymeleaf. Automated testing was done for this project using JUnit, Mockito, and Selenium, and JACOCO was used for test coverage analysis.'
  },
  {
    category: 'web',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    image: p8,
    altText: 'My Portfolio',
    title: 'My Portfolio',
    description: 'A responsive website to showcase my skills, projects, and achievements.',
    github: 'https://github.com/disara7/portfolio',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'web',
    award: 'yes',
    type: 'GROUP PROJECT | COMPLETED',
    image: p9,
    altText: 'Haven - Mental health oasis',
    title: 'Haven - Mental Health Oasis',
    description: 'It is a comprehensive online web-based platform that leverages AI and VR.',
    github: 'https://github.com/disara7/Haven',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  

  //Other projects
  {
    category: 'other',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    image: p14,
    altText: 'Killer Sudoku Helper',
    title: 'Killer Sudoku Helper - Python + Next.js Project',
    description: 'A killer sudoku helper created by connecting a Python Script as the Backend to a Next.js/Typescript Frontend.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'other',
    award: 'yes',
    type: 'GROUP PROJECT | COMPLETED',
    image: blank,
    altText: 'Shut - Car Racing Simulation Game',
    title: 'Shut - Car Racing Simulation Game',
    description: 'To learn different Flutter things.',
    github: 'https://github.com/disara7',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'other',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    showImage: false,
    image: p12,
    altText: 'Tumor Identifying AI Model',
    title: 'Tumor Identifying AI Model',
    description: 'An AI model created using Tensorflow/Keras and scikit-learn. This AI model is trained on real data from breast cancer diagnosis.',
    github: 'https://github.com/disara7/Tumor_identifying_AI',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'other',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    showImage: false,
    image: p13,
    altText: 'JARVIS - AI Model',
    title: 'JARVIS - AI Model',
    description: 'This AI uses speech recognition and speech to text, to communicate with ChatGPT and talk back with ChatGPT\'s responses.',
    github: 'https://github.com/disara7/JARVIS',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  {
    category: 'other',
    award: 'no',
    type: 'INDIVIDUAL PROJECT | COMPLETED',
    showImage: false,
    image: blank,
    altText: 'Simple Tic-Tac-Toe Game',
    title: 'Simple Tic-Tac-Toe Game',
    description: 'To learn different Flutter things.',
    github: 'https://github.com/disara7/tic-tac-toe',
    adobe: 'https://adobe-link',
    medium: 'https://medium-link',
    video: 'https://video-link',
  },
  

   //UI/UX designs
  //  {
  //   category: 'ui',
  //   award: 'no',
  //   type: 'GROUP PROJECT | COMPLETED',
  //   showImage: false,
  //   image: chemwaste,
  //   altText: 'ChemWaste - Sustainably Dispose Chemical Waste',
  //   title: 'ChemWaste - Sustainably Dispose Chemical Waste',
  //   description: 'ChemWaste connects labs and recyclers or other labs to properly dispose chemical waste that are generated in chemical laboratories sustainably.',
  //   github: 'https://github.com/disara7/Tumor_identifying_AI',
  //   adobe: 'https://adobe-link',
  //   medium: 'https://medium-link',
  //   video: 'https://video-link',
  // },
  // {
  //   category: 'ui',
  //   award: 'no',
  //   type: 'GROUP PROJECT | COMPLETED',
  //   showImage: false,
  //   image: chemwaste,
  //   altText: 'Sentry - A Solution to Human-Elephant Conflicts in Sri Lanka',
  //   title: 'Sentry - A Solution to Human-Elephant Conflicts in Sri Lanka',
  //   description: 'Sentry is a web-based solution to Human-Elephant Conflicts in Sri Lanka.',
  //   github: 'https://github.com/disara7/Tumor_identifying_AI',
  //   adobe: 'https://adobe-link',
  //   medium: 'https://medium-link',
  //   video: 'https://video-link',
  //   longdescription: 'We identified Human-Elephant Conflicts as an environmental issue in Sri Lanka, which is currently a large threat in certain rural areas of Sri Lanka. Both people and elephants, very often lose their lives and properties in this conflict. So, we, the "Pixel Concepts" came up with Sentry, the web-based platform which works on an island wide level to track the areas with elephant attacks, find why this happens, make people aware of how to avoid these attacks and how to deal with the aftermath, and to allow the philanthropic hearts to help rebuild the shattered lives of the victims of these attacks. Sentry was designed after a detailed background research and a UX Research which involved interviews with potential users, and by following UI Design principles thoroughly, along with the complete procedure of UI design which involved traditional wireframing to creating high fidelity mock-ups with Adobe XD.'
  // },
];

export default projects;
